### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by BenOvermyer** [BenOvermyer/MonkBlog#10]
A theme system should be implemented so that themes can be versioned separately from Monk core.

**Comment by ericdowell** [comment]
[Laravel GitHub](https://github.com/GrahamCampbell/Laravel-GitHub) could be an easy way to get themes install and managed within Monk Blog. I think we should also define a theme spec which should be stored within a yaml or json file.
e.g.

```json
{
   "name" : "my-awesome-theme",
   "type" : "monk-theme",
   "version" : "0.1",
   "so-on" : "value"
}
```
or
```yaml
   name : my-awesome-theme
   type : monk-theme
   version : 0.1
   so-on : value
```
